name: "Got Issues Action"
description: "Add an issue to the gotissues website."

runs:
  using: "node16"
  main: "dist/index.js"

inputs:
  repo_name:
    description: "The name of the repository."
    required: true
  repo_owner:
    description: "The owner of the repository."
    required: true
  issue_creator:
    description: "The creator of the issue."
    required: true
  issue:
    description: "The issue object."
    required: true
